### ISSUE TITLE
support all HTTP Methods

### ISSUE THREAD

**Issue by fponticelli** [fponticelli/restx#5]
Add support at least for the following metas:
- [x] @:all
- [x] @:get
- [x] @:post
- [x] @:put
- [x] @:options
- [x] @:head
- [x] @:delete

**Comment by mlms13** [comment]
`get`/`post`/`put`/`delete` should all work, however without bodyParser, it's a bit difficult to be sure data is being received.

`options` and `head` are both handled, but since those are special cases, we might want to do something for them. For example, if you created metadata like `@:head("/some/path")` without adding a function to handle the request, we could automatically inject a function to send back the headers. Did you have something like that in mind @fponticelli?

Additionally, for `options` we had talked about looking at tools like [RestDoc](http://restdoc.github.io/spec.html) and [Node Docrouter](https://github.com/anodejs/node-docrouter)

**Comment by mlms13** [comment]
Looks like Express automatically handles HEAD and OPTIONS for every route you create.  `@:all` is coming in the next PR as soon as I update the README.  I'll open a new issue for the RestDoc stuff, but other than that, this issue is done.
